---
title: "XGBoost"
author: "VDOT team 2"
date: "2022/5/5"
output: html_document
---
```{r}
rm(list = ls())
library(dplyr)
library(tidyr)
library(xgboost)
library(caret)
library(ggplot2)
```

##### Loading Dataset #####
```{r pressure, echo=FALSE}
#Read in Data
data <- read.csv('HistoricalData.csv', header = TRUE, stringsAsFactors = TRUE)
data <- subset(data, select=-c(Date,TRAILER,BUS,TRUCK,PED.BYC,LOD,SchoolEvent,snow,Rush,CountWeekDay)) #Remove non-predictor columns

#Convert Datatype
data$Hour <- as.character(data$Hour)
data$Month <- as.character(data$Month)
data$Day <- as.character(data$Day)
data$Week.Number <- as.character(data$Week.Number)
data$Day.of.Week <- as.character(data$Day.of.Week)
data$Holiday <- as.character(data$Holiday)
data$covid <- as.factor(data$covid)
#data$Rush <- as.factor(data$Rush)

#Randomly Sample Data (80/20)
trainIndex = sample(1:nrow(data), size = nrow(data)*0.8)

#Define Train Set
train.x <- data[trainIndex, -2] #Create train set, remove target variable
train.y <- data$TOTAL[trainIndex]
train.x = data.matrix(train.x) #Convert from DF to matrix
xgb_train = xgb.DMatrix(data = train.x, label = train.y)

#Define Test Set
test.x <- data[-trainIndex, -2] #Create test set, remove target variable
test.y <- data$TOTAL[-trainIndex]
test.x = data.matrix(test.x)  #Convert from DF to matrix
xgb_test = xgb.DMatrix(data = test.x, label = test.y)

```

### XGBoost Model ###
```{r}
set.seed(4)

#Cross Validation
model <- xgb.cv(eval_metric = "mae",
              max_depth = 6,
              data = xgb_train,
              nrounds = 500,
              watchlist = list(train=xgb_train, test=xgb_test),
              maximize = FALSE,
              nfold = 3,
              early_stopping_rounds = 10,
              print_every_n = 1,
              verbose = 0)
bestRound <- which.min(model$evaluation_log$test_mae_mean)

#Train
model <- xgb.train(eval_metric = "mae",
                   max_depth = 6,
                   data = xgb_train, 
                   nrounds = bestRound, 
                   watchlist= list(train=xgb_train, test=xgb_test),
                   verbose = 0)
mae <- min(model$evaluation_log$test_mae)

save(model, file = "HourModel2.rda") #Save model
```

### Importance Table and Plot
```{r}
importance_matrix <- xgb.importance(model = model)
print(importance_matrix)
xgb.plot.importance(importance_matrix = importance_matrix)
```

```{r}
#Make Predictions
  
compare <- data[-trainIndex, -2]
compare$pred_y <- predict(model, newdata = test.x)
compare$actual_y <- test.y

compare <- compare %>% group_by(Hour) %>% summarise(pred_y = mean(pred_y))


compare <- compare %>% mutate(mae = abs(actual_y-pred_y)) %>% group_by(Hour) %>% summarise(mae = mean(mae))
compare$Hour <- as.numeric(compare$Hour)


#Make Predictions
newdata <- read.csv("PredictiveData.csv")
predictions <- subset(newdata, select=c(Date, Hour))
newdata <- subset(newdata, select=-c(Date,snow,X,Rush))

#Convert Datatype
newdata$Hour <- as.character(newdata$Hour)
newdata$Month <- as.character(newdata$Month)
newdata$Day <- as.character(newdata$Day)
newdata$Week.Number <- as.character(newdata$Week.Number)
newdata$Day.of.Week <- as.character(newdata$Day.of.Week)
newdata$Holiday <- as.character(newdata$Holiday)
newdata$covid <- as.factor(newdata$covid)



newdata <- data.matrix(newdata, rownames.force = NA)
  
predictions["TOTAL_Hour_Predict"] <- predict(model, newdata = newdata)
  
```

